const data =  {
        "total": 26,
        "list": [
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "DY",
                "platformName": "抖音",
                "shopId": null,
                "categoryId": "1534078794225389592",
                "categoryName": null,
                "goodsId": "1592044081830891521",
                "goodsName": null,
                "goodsSkuId": "1592044082057383937",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": null,
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华北": 2,
                            "华南": 2
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "DY",
                "platformName": "抖音",
                "shopId": null,
                "categoryId": "1534078794225389592",
                "categoryName": null,
                "goodsId": "1592044081830891521",
                "goodsName": null,
                "goodsSkuId": "1592044082057383937",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": "20220511",
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华北": 2,
                            "华南": 2
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "DY",
                "platformName": "抖音",
                "shopId": null,
                "categoryId": "1572476588988723202",
                "categoryName": null,
                "goodsId": "1592063658308567042",
                "goodsName": null,
                "goodsSkuId": "1592063658543448065",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": null,
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华南": 1
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "DY",
                "platformName": "抖音",
                "shopId": null,
                "categoryId": "1572476588988723202",
                "categoryName": null,
                "goodsId": "1592063658308567042",
                "goodsName": null,
                "goodsSkuId": "1592063658543448065",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": "S_PINK1",
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华南": 1
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "DY",
                "platformName": "抖音",
                "shopId": null,
                "categoryId": "1583408822193152002",
                "categoryName": null,
                "goodsId": "1605138805798195201",
                "goodsName": null,
                "goodsSkuId": "1605138806209236993",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": null,
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华北": 2,
                            "华中": 10,
                            "西南": 100
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "DY",
                "platformName": "抖音",
                "shopId": null,
                "categoryId": "1583408822193152002",
                "categoryName": null,
                "goodsId": "1605138805798195201",
                "goodsName": null,
                "goodsSkuId": "1605138806209236993",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": "tt202212200002",
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华北": 2,
                            "华中": 10,
                            "西南": 100
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "DY",
                "platformName": "抖音",
                "shopId": null,
                "categoryId": "1583408822193152002",
                "categoryName": null,
                "goodsId": "1613477191374049282",
                "goodsName": null,
                "goodsSkuId": "1613477191407603713",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": null,
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华北": 2
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "DY",
                "platformName": "抖音",
                "shopId": null,
                "categoryId": "1583408822193152002",
                "categoryName": null,
                "goodsId": "1613477191374049282",
                "goodsName": null,
                "goodsSkuId": "1613477191407603713",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": "14614eqwerfdsdf564",
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华北": 2
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "DY",
                "platformName": "抖音",
                "shopId": null,
                "categoryId": "1583412407782006786",
                "categoryName": null,
                "goodsId": "1620730529161273346",
                "goodsName": null,
                "goodsSkuId": "1620730529308073985",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": null,
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华北": 5,
                            "华东": 2
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "DY",
                "platformName": "抖音",
                "shopId": null,
                "categoryId": "1583412407782006786",
                "categoryName": null,
                "goodsId": "1620730529161273346",
                "goodsName": null,
                "goodsSkuId": "1620730529308073985",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": "1azwsx",
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华北": 5,
                            "华东": 2
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "DY",
                "platformName": "抖音",
                "shopId": null,
                "categoryId": "1607623664420511746",
                "categoryName": null,
                "goodsId": "1626475828429438977",
                "goodsName": null,
                "goodsSkuId": "1626475828458799105",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": null,
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华中": 2
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "DY",
                "platformName": "抖音",
                "shopId": null,
                "categoryId": "1607623664420511746",
                "categoryName": null,
                "goodsId": "1626475828429438977",
                "goodsName": null,
                "goodsSkuId": "1626475828458799105",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": "1234523413",
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华中": 2
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "DY",
                "platformName": "抖音",
                "shopId": null,
                "categoryId": "1607623664420511746",
                "categoryName": null,
                "goodsId": "1626475828429438977",
                "goodsName": null,
                "goodsSkuId": "1626491750657540097",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": null,
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华中": 2
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "DY",
                "platformName": "抖音",
                "shopId": null,
                "categoryId": "1607623664420511746",
                "categoryName": null,
                "goodsId": "1626475828429438977",
                "goodsName": null,
                "goodsSkuId": "1626491750657540097",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": "dsfggd32123",
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华中": 2
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "JD_OPERATE",
                "platformName": "京东自营",
                "shopId": null,
                "categoryId": "1534078794225389576",
                "categoryName": null,
                "goodsId": "1534094463599976449",
                "goodsName": null,
                "goodsSkuId": "1534094463608365058",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": "6924964565143",
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "西南": 1
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "JD_OPERATE",
                "platformName": "京东自营",
                "shopId": null,
                "categoryId": "1534078794225389577",
                "categoryName": null,
                "goodsId": "1534094463612559363",
                "goodsName": null,
                "goodsSkuId": "1541376664351862790",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": "22223123123",
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "西南": 50
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "JD_POP",
                "platformName": "京东POP",
                "shopId": null,
                "categoryId": "1534090657562484738",
                "categoryName": null,
                "goodsId": "1549609905596649473",
                "goodsName": null,
                "goodsSkuId": "1549609905659564033",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": null,
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华南": 4
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "JD_POP",
                "platformName": "京东POP",
                "shopId": null,
                "categoryId": "1534090657562484738",
                "categoryName": null,
                "goodsId": "1549609905596649473",
                "goodsName": null,
                "goodsSkuId": "1549609905659564033",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": "6975455072039",
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华南": 4
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "JD_POP",
                "platformName": "京东POP",
                "shopId": null,
                "categoryId": "1534090657562484738",
                "categoryName": null,
                "goodsId": "1549609905596649473",
                "goodsName": null,
                "goodsSkuId": "1551866676319580161",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": null,
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华南": 2
                        }
                    }
                ]
            },
            {
                "id": null,
                "createId": null,
                "createName": null,
                "createTime": null,
                "updateId": null,
                "updateName": null,
                "updateTime": null,
                "pageIndex": 0,
                "pageSize": 0,
                "visible_category_id": null,
                "orderKey": null,
                "platformId": null,
                "platformCode": "JD_POP",
                "platformName": "京东POP",
                "shopId": null,
                "categoryId": "1534090657562484738",
                "categoryName": null,
                "goodsId": "1549609905596649473",
                "goodsName": null,
                "goodsSkuId": "1551866676319580161",
                "goodsSkuName": null,
                "erpNo": null,
                "barCode": "1361583",
                "regionCode": null,
                "regionName": null,
                "avgPrice": null,
                "saleQty": null,
                "saleAmount": null,
                "date": null,
                "type": null,
                "details": [
                    {
                        "cycleTime": "汇总",
                        "cycleTimeEnd": null,
                        "cycletimeBegin": null,
                        "details": {
                            "华南": 2
                        }
                    }
                ]
            }
        ],
        "pageNum": 1,
        "pageSize": 20,
        "size": 20,
        "startRow": 1,
        "endRow": 20,
        "pages": 2,
        "prePage": 0,
        "nextPage": 2,
        "isFirstPage": true,
        "isLastPage": false,
        "hasPreviousPage": false,
        "hasNextPage": true,
        "navigatePages": 8,
        "navigatepageNums": [
            1,
            2
        ],
        "navigateFirstPage": 1,
        "navigateLastPage": 2
    }
    
    export default data