export default [
  {
    path: '/',
    component: '../layout/index',
    menu: {
      flatMenu: true,
    },
    routes: [
      {
        path: '/',
        redirect: '/home',
      },
      {
        path: '/home',
        name: '首页',
        component: './dashboard',
        hideInMenu: true,
      },
      {
        path: '/login',
        name: '登录',
        layout: false,
        component: './Login',
        hideInMenu: true,
      },
      {
        path: '/supplier-manage',
        name: '供应商管理',
        icon: 'team',
        routes: [
          {
            path: 'supplier',
            name: '供应商列表',
            component: './SupplierManage/Supplier',
            keepAlive: true,
            access: 'routeFilter',
          },
          {
            path: 'payment-method-manage',
            name: '结算方式管理',
            component: './SupplierManage/PaymentMethod',
            keepAlive: true,
            access: 'routeFilter',
          },
          {
            path: 'basic',
            name: '补充供应商信息',
            hideInMenu: true,
            component: './SupplierManage/Supplier/Details/Index',
            parentKeys: ['/supplier-manage/supplier'],
            keepAlive: false,
          },
          {
            path: 'edit-basic',
            name: '编辑供应商信息',
            hideInMenu: true,
            component: './SupplierManage/Supplier/Details/Index',
            parentKeys: ['/supplier-manage/supplier'],
            keepAlive: false,
          },
          {
            path: 'detail-basic',
            name: '供应商详情',
            hideInMenu: true,
            component: './SupplierManage/Supplier/Details/Index',
            parentKeys: ['/supplier-manage/supplier'],
            keepAlive: false,
          },
          {
            path: 'complaint',
            name: '供应商反馈管理',
            access: 'routeFilter',
            component: './SupplierManage/Complaint',
            keepAlive: false,
          },
          {
            path: 'account',
            name: '供应商登录账号',
            access: 'routeFilter',
            component: './SupplierManage/Account',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/products',
        name: '商品管理',
        icon: 'barcode',
        routes: [
          {
            path: 'products',
            redirect: '/products/cooperate-product',
          },
          {
            path: 'cooperate-product-cn',
            name: 'CN采购商品',
            access: 'routeFilter',
            noAccessBtnCode: true,
            component: './Products/CooperateProduct/index-cn',
            keepAlive: true,
          },
          {
            path: 'parts-product-cn',
            name: 'CN配件商品',
            access: 'routeFilter',
            component: './Products/PartsProduct/index-cn',
            keepAlive: true,
          },
          {
            path: 'cooperate-product-in',
            name: 'IN采购商品',
            access: 'routeFilter',
            component: './Products/CooperateProduct/index-in',
            keepAlive: true,
          },
          {
            path: 'cooperate-product/detail',
            name: '采购商品详情',
            component: './Products/CooperateProduct/detail',
            hideInMenu: true,
            parentKeys: ['/products/cooperate-product'],
          },
          {
            path: 'price-change',
            name: '价格变更',
            access: 'routeFilter',
            component: './Products/PriceChange/index',
            keepAlive: true,
          },
          {
            path: 'vendor-backup',
            name: '供应商备份',
            access: 'routeFilter',
            component: './Products/VendorBackup',
            keepAlive: true,
          },
          {
            path: 'vendor-backup/price-approval',
            name: '价格审批-供应商备份',
            component: './Products/VendorBackup/PriceApproval/detail',
            parentKeys: ['/products/vendor-backup'],
            hideInMenu: true,
            keepAlive: true,
          },
          {
            path: 'vendor-backup/signature',
            name: '签样确认-供应商备份',
            component: './Products/VendorBackup/Signature/detail',
            parentKeys: ['/products/vendor-backup'],
            hideInMenu: true,
            keepAlive: true,
          },
          /*{
          path: 'supplier-product',
          name: '供应商商品',
          access: 'routeFilter',
          component: './Products/SupplierProduct/index',
          keepAlive: true,
        },
        {
          path: 'supplier-product/detail',
          name: '供应商商品详情',
          component: './Products/SupplierProduct/detail',
          hideInMenu: true,
          parentKeys: ['/products/supplier-product'],
        },*/
        ],
      },
      {
        path: '/sign-establish',
        name: '产品管理',
        icon: 'FileAddOutlined',
        routes: [
          {
            path: '/sign-establish',
            redirect: '/sign-establish/product-list',
          },

          {
            path: 'product-list',
            name: '产品列表',
            component: './ProductList',
            keepAlive: true,
            access: 'routeFilter',
          },
          {
            path: 'product-detail',
            name: '产品详情',
            hideInMenu: true,
            component: './ProductList/Detail/detail',
            parentKeys: ['/sign-establish/product-list'],
          },
          {
            path: 'product-detail-marketing',
            name: '产品详情',
            hideInMenu: true,
            component: './ProductList/Detail/detail',
            parentKeys: ['/sign-establish/product-list'],
          },
          {
            path: 'product-edit',
            name: '修改款式信息',
            hideInMenu: true,
            component: './ProductList/Detail/editSku',
            parentKeys: ['/sign-establish/product-list'],
            keepAlive: true,
          },
          {
            path: 'productLine',
            name: '产品线管理',
            access: 'routeFilter',
            component: './ProductLine',
            keepAlive: false,
          },
          {
            path: 'establish',
            name: '产品立项',
            access: 'routeFilter',
            component: './EstablishManage',
            keepAlive: true,
          },
          {
            path: 'sample-list',
            name: '样品单管理',
            access: 'routeFilter',
            component: './SampleList',
            keepAlive: true,
          },
          {
            path: 'sample-detail',
            name: '样品单详情',
            hideInMenu: true,
            component: './SampleList/detail',
            keepAlive: true,
          },
          {
            path: 'price-approval',
            name: '价格审批',
            access: 'routeFilter',
            component: './PriceApproval',
            keepAlive: true,
          },
          {
            path: 'price-approval/detail',
            name: '价格审批详情',
            component: './PriceApproval/detail',
            hideInMenu: true,
            keepAlive: true,
          },
          {
            path: 'signature',
            name: '签样管理',
            access: 'routeFilter',
            component: './Signature',
            keepAlive: true,
          },
          {
            path: 'signature/detail',
            name: '签样详情',
            component: './Signature/detail',
            hideInMenu: true,
            keepAlive: true,
          },
          {
            path: 'establish-detail-sku',
            name: '新增款式',
            hideInMenu: true,
            component: './EstablishManage/establishDetail',
            parentKeys: ['/sign-establish/product-list'],
            keepAlive: true,
          },
          {
            path: 'establish-detail-version',
            name: '版本迭代',
            hideInMenu: true,
            component: './EstablishManage/establishDetail',
            parentKeys: ['/sign-establish/product-list'],
            keepAlive: true,
          },
          {
            path: 'establish-detail',
            name: '立项详情',
            hideInMenu: true,
            component: './EstablishManage/establishDetail',
            parentKeys: ['/sign-establish/establish'],
          },
          {
            path: 'establish-detail-edit',
            name: '修改立项',
            hideInMenu: true,
            component: './EstablishManage/establishDetail',
            parentKeys: ['/sign-establish/establish'],
          },
          {
            path: 'establish-detail-add',
            name: '新增立项',
            hideInMenu: true,
            component: './EstablishManage/establishDetail',
            parentKeys: ['/sign-establish/product-list'],
            keepAlive: true,
          },
          {
            path: 'finalize-detail-edit',
            name: '编辑定稿',
            hideInMenu: true,
            component: './EstablishManage/finalizeDetail',
            keepAlive: true,
          },
          {
            path: 'finalize-detail',
            name: '定稿详情',
            hideInMenu: true,
            component: './EstablishManage/finalizeDetail',
          },
          {
            path: 'apply-mould',
            name: '开模申请',
            hideInMenu: true,
            component: './applyMould/index',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/product-link',
        name: '产品营销管理',
        icon: 'DisconnectOutlined',
        routes: [
          {
            path: 'links/cn',
            name: 'CN链接管理',
            access: 'routeFilter',
            component: './ProductLink/Links',
            keepAlive: true,
          },
          {
            path: 'links/in',
            name: 'IN链接管理',
            access: 'routeFilter',
            component: './ProductLink/Links',
            keepAlive: true,
          },
          {
            path: 'links-detail',
            name: '链接详情',
            component: './ProductLink/Links/detail',
            parentKeys: ['/product-link/links'],
            keepAlive: false,
            hideInMenu: true,
          },
          {
            path: 'platform',
            name: '平台管理',
            access: 'routeFilter',
            component: './ProductLink/Platform',
            keepAlive: true,
          },
          {
            path: 'shop',
            name: '店铺管理',
            access: 'routeFilter',
            component: './ProductLink/Shop',
            keepAlive: true,
          },
          {
            path: 'instantSales-amazon',
            name: 'Amazon销售看板',
            access: 'routeFilter',
            component: './ProductLink/instantSales-amazon',
            keepAlive: true,
          },
          {
            path: 'adAdmin-amazon',
            name: 'Amazon广告管理',
            access: 'routeFilter',
            component: './ProductLink/adAdmin-amazon',
            keepAlive: true,
          },
          {
            path: 'adAdmin-modify',
            name: '定时策略',
            access: 'routeFilter',
            component: './ProductLink/adAdmin-modify',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/contract-manage',
        name: '合同管理',
        icon: 'fileProtect',
        routes: [
          {
            path: '/contract-manage',
            redirect: '/contract-manage/list',
          },
          {
            path: 'list',
            name: '合同列表',
            access: 'routeFilter',
            component: './ContractManage/List',
            keepAlive: true,
          },
          {
            path: 'depot',
            name: '合同模板库',
            access: 'routeFilter',
            component: './ContractManage/Depot',
            keepAlive: true,
          },
          {
            path: 'sign',
            name: '签约主体',
            access: 'routeFilter',
            component: './ContractManage/Sign',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/stock-up-in',
        name: 'IN备货管理',
        icon: 'global',
        routes: [
          {
            path: '/stock-up-in',
            redirect: '/stock-up-in/storageCapacity',
          },
          {
            path: 'storageCapacity',
            name: '库容数据',
            icon: 'shop',
            routes: [
              {
                path: '/stock-up-in/storageCapacity',
                redirect: '/stock-up-in/storageCapacity/capacityList',
              },
              {
                path: 'capacityList',
                name: '库容数据',
                access: 'routeFilter',
                component: './StockUpIn/StorageCapacity/CapacityList',
                keepAlive: true,
              },
              {
                path: 'IPIList',
                name: 'IPI数据',
                access: 'routeFilter',
                component: './StockUpIn/StorageCapacity/IPIList',
                keepAlive: true,
              },
            ],
          },
          {
            path: 'storage-manage',
            name: 'IN库存信息',
            component: './StockUpIn/StorageManage/ReportList',
            keepAlive: true,
            access: 'routeFilter',
          },
          {
            path: 'storageRules',
            name: '备货规则',
            icon: 'control',
            routes: [
              {
                path: '/stock-up-in/storageRules',
                redirect: '/stock-up-in/storageRules/seasonRatio',
              },
              {
                path: 'seasonRatio',
                name: '淡旺季系数',
                component: './StockUpIn/StorageRules/SeasonRatio',
                access: 'routeFilter',
                keepAlive: true,
              },
              {
                path: 'logisticsPeriod',
                name: '物流时效',
                component: './StockUpIn/StorageRules/LogisticsPeriod',
                keepAlive: true,
              },

              {
                path: 'warehouse',
                name: 'IN平台仓',
                component: './StockUpIn/StorageRules/Warehouse',
                access: 'routeFilter',
                keepAlive: true,
              },
              {
                path: 'safeStock',
                name: 'IN备货配置',
                component: './StockUpIn/StorageRules/SafeStock',
                access: 'routeFilter',
                keepAlive: true,
              },
            ],
          },

          {
            path: 'stock-up-warning',
            name: 'IN备货库存预警报表',
            component: './StockUpIn/StockUpWarning',
            keepAlive: true,
            access: 'routeFilter',
          },

          {
            path: 'stockUp',
            name: '备货管理',
            icon: 'shop',
            routes: [
              {
                path: '/stock-up-in/stockUp',
                redirect: '/stock-up-in/stockUp/suggestList',
              },
              {
                path: 'suggestList',
                name: 'IN备货建议',
                access: 'routeFilter',
                component: './StockUpIn/StockUp/SuggestList',
                keepAlive: true,
              },
              {
                path: 'suggest-detail',
                name: '备货建议详情',
                component: './StockUpIn/StockUp/SuggestList/Detail',
                parentKeys: ['/stock-up-in/stockUp/suggestList'],
                hideInMenu: true,
              },
            ],
          },
        ],
      },

      {
        path: '/stock-up-cn',
        name: 'CN备货基础数据',
        icon: 'global',
        routes: [
          {
            path: '/stock-up-cn',
            redirect: '/stock-up-cn/seasonRatioCn',
          },
          {
            path: 'seasonRatioCn',
            name: 'CN淡旺季系数',
            component: './StockUpCn/StockCnBase/SeasonRatio',
            access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'stockConfigCn',
            name: 'CN备货配置',
            component: './StockUpCn/StockCnBase/StockConfig',
            access: 'routeFilter',
            keepAlive: true,
          },
        ],

      },

      {
        path: '/purchase-manage',
        name: '采购管理',
        icon: 'ShoppingOutlined',
        routes: [
          {
            path: '/purchase-manage',
            redirect: '/purchase-manage/plan',
          },
          {
            path: 'plan-cn',
            name: 'CN采购计划',
            access: 'routeFilter',
            component: './PurchaseManage/Plan/planCn',
            keepAlive: true,
          },
          {
            path: 'plan-in',
            name: 'IN采购计划',
            access: 'routeFilter',
            component: './PurchaseManage/Plan/planIn',
            keepAlive: true,
          },
          {
            path: 'plan-addOne',
            name: '生成采购单',
            hideInMenu: true,
            component: './PurchaseManage/Plan/addOne',
            parentKeys: ['/purchase-manage/plan'],
          },
          {
            path: 'plan-addOne-in',
            name: '生成采购单',
            hideInMenu: true,
            component: './PurchaseManage/Plan/addOne',
            parentKeys: ['/purchase-manage/plan-in'],
          },
          {
            path: 'plan-addList',
            name: '生成采购单',
            hideInMenu: true,
            component: './PurchaseManage/Plan/addList',
            parentKeys: ['/purchase-manage/plan'],
          },
          {
            path: 'order',
            name: '采购单',
            access: 'routeFilter',
            component: './PurchaseManage/Order',
            keepAlive: true,
          },
          {
            path: 'add-parts-order',
            name: '创建配件采购单',
            hideInMenu: true,
            component: './PurchaseManage/Order/addPartsOrder',
          },
          {
            path: 'update-order',
            name: '采购变更单',
            access: 'routeFilter',
            component: './PurchaseManage/UpdateOrder',
            keepAlive: true,
          },
          {
            path: 'update-detail',
            name: '采购单变更',
            hideInMenu: true,
            component: './PurchaseManage/UpdateOrder/update',
            parentKeys: ['/purchase-manage/Order'],
          },
          {
            path: 'order-detail',
            name: '采购单详情',
            hideInMenu: true,
            component: './PurchaseManage/Order/detail',
            parentKeys: ['/purchase-manage/order'],
          },
          {
            path: 'delivery-plan-cn',
            name: 'CN发货计划',
            access: 'routeFilter',
            component: './PurchaseManage/DeliveryPlan/home',
            keepAlive: true,
          },
          {
            path: 'delivery-plan-in',
            name: 'IN发货计划',
            access: 'routeFilter',
            component: './PurchaseManage/DeliveryPlan/abroad',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/library-manage',
        name: '库存管理',
        icon: 'FileTextOutlined',
        routes: [
          {
            path: '/library-manage',
            redirect: '/library-manage/list',
          },
          {
            path: 'list',
            name: 'CN库存信息',
            access: 'routeFilter',
            noAccessBtnCode: true,
            component: './LibraryManager/List',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/transfer-manage',
        name: '调拨单',
        icon: 'DeliveredProcedureOutlined',
        routes: [
          {
            path: '/transfer-manage',
            redirect: '/transfer-manage/order',
          },
          {
            path: 'order',
            name: '仓内调拨',
            access: 'routeFilter',
            component: './TransferOrder/index',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/stock-manage',
        name: '出入库管理',
        icon: 'CloudServerOutlined',
        routes: [
          {
            path: 'cn',
            name: 'CN平台入库单',
            access: 'routeFilter',
            component: './StockManager/Cn',
            keepAlive: true,
          },
          {
            path: 'in',
            name: 'IN平台入库单',
            access: 'routeFilter',
            component: './StockManager/In',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/reconciliation-manage',
        name: '对账管理',
        icon: 'DollarOutlined',
        routes: [
          {
            path: 'purchaseCn',
            name: 'CN采购对账',
            access: 'routeFilter',
            component: './ReconciliationManage/Purchase/cn',
            keepAlive: true,
          },
          {
            path: 'purchaseCn-detail',
            name: '对账详情',
            hideInMenu: true,
            component: './ReconciliationManage/Purchase/detail',
            parentKeys: ['/reconciliation-manage/purchaseCn'],
          },
          {
            path: 'purchaseIn',
            name: 'IN采购对账',
            access: 'routeFilter',
            component: './ReconciliationManage/Purchase/in',
            keepAlive: true,
          },
          {
            path: 'purchaseIn-detail',
            name: '对账详情',
            hideInMenu: true,
            component: './ReconciliationManage/Purchase/detail',
            parentKeys: ['/reconciliation-manage/purchaseIn'],
          },
          {
            path: 'askAction',
            name: '采购请款',
            access: 'routeFilter',
            component: './ReconciliationManage/AskAction',
            keepAlive: true,
          },
          {
            path: 'askAction-edit',
            name: '编辑请款',
            hideInMenu: true,
            component: './ReconciliationManage/AskAction/edit',
            parentKeys: ['/reconciliation-manage/askAction'],
          },
          {
            path: 'askAction-detail',
            name: '请款详情',
            hideInMenu: true,
            component: './ReconciliationManage/AskAction/detail',
            parentKeys: ['/reconciliation-manage/askAction'],
          },
          {
            path: 'deduction',
            name: '扣款管理',
            access: 'routeFilter',
            component: './ReconciliationManage/Deduction',
            keepAlive: true,
          },
          {
            path: 'deduction-edit',
            name: '编辑扣款',
            hideInMenu: true,
            component: './ReconciliationManage/Deduction/edit',
            parentKeys: ['/reconciliation-manage/deduction'],
          },
          {
            path: 'deduction-detail',
            name: '扣款详情',
            hideInMenu: true,
            component: './ReconciliationManage/Deduction/detail',
            parentKeys: ['/reconciliation-manage/deduction'],
          },
          {
            path: 'payment',
            name: '付款统计',
            access: 'routeFilter',
            component: './ReconciliationManage/Payment',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/logistics-manage-in',
        name: 'IN物流管理',
        icon: 'NodeIndexOutlined',
        routes: [
          {
            path: 'logistics-plan-in-stock',
            name: 'IN物流计划(入库单)',
            access: 'routeFilter',
            component: './LogisticsPlanIn/stock',
            keepAlive: true,
          },
          {
            path: 'logistics-plan-in-delivery',
            name: 'IN物流计划(发货计划)',
            access: 'routeFilter',
            component: './LogisticsPlanIn/delivery',
            keepAlive: true,
          },
          {
            path: 'lsp',
            name: 'IN物流商',
            access: 'routeFilter',
            component: './LogisticsManageIn/LSP',
            keepAlive: true,
          },
          {
            path: 'lsp-add',
            name: '新增物流商',
            component: './LogisticsManageIn/LSP/details',
            keepAlive: true,
            parentKeys: ['/logistics-manage-in/lsp'],
            hideInMenu: true,
          },
          {
            path: 'lsp-edit',
            name: '编辑物流商',
            component: './LogisticsManageIn/LSP/details',
            keepAlive: true,
            parentKeys: ['/logistics-manage-in/lsp'],
            hideInMenu: true,
          },
          {
            path: 'lsp-detail',
            name: '物流商详情',
            component: './LogisticsManageIn/LSP/details',
            keepAlive: true,
            parentKeys: ['/logistics-manage-in/lsp'],
            hideInMenu: true,
          },
          {
            path: 'port-manage',
            name: 'IN港口管理',
            access: 'routeFilter',
            component: './LogisticsManageIn/PortManage',
            keepAlive: true,
          },
          {
            path: 'start-port-ware',
            name: 'IN起运港仓库 ',
            access: 'routeFilter',
            component: './LogisticsManageIn/StartPortWare',
            keepAlive: true,
          },
          {
            path: 'des-port-warehouse',
            name: 'IN目的港仓库',
            access: 'routeFilter',
            component: './LogisticsManageIn/DesPortWare',
            keepAlive: true,
          },
          {
            path: 'company',
            name: 'IN船公司/快递公司',
            access: 'routeFilter',
            component: './LogisticsManageIn/ShipOrDeliveryCompany',
            keepAlive: true,
          },
          {
            path: 'logistics-order',
            name: 'IN物流单',
            access: 'routeFilter',
            component: './LogisticsManageIn/LogisticsOrder/Index',
            keepAlive: true,
          },
          {
            path: 'logistics-order-edit',
            name: 'IN物流单编辑',
            component: './LogisticsManageIn/LogisticsOrder/Details',
            keepAlive: true,
            parentKeys: ['/logistics-manage-in/logistics-order'],
            hideInMenu: true,
          },
          {
            path: 'logistics-order-detail',
            name: 'IN物流单详情',
            component: './LogisticsManageIn/LogisticsOrder/Details',
            keepAlive: true,
            parentKeys: ['/logistics-manage-in/logistics-order'],
            hideInMenu: true,
          },
          {
            path: 'logistics-timeliness',
            name: 'IN物流时效统计',
            access: 'routeFilter',
            component: './LogisticsManageIn/TimelinessStatistics',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/logistics-manage-cn',
        name: 'CN物流管理',
        icon: 'NodeExpandOutlined',
        routes: [
          {
            path: 'lsp',
            name: 'CN物流商',
            access: 'routeFilter',
            component: './LogisticsManageCn/LSP',
            keepAlive: true,
          },
          {
            path: 'lost-details',
            name: 'CN物流丢失明细',
            access: 'routeFilter',
            component: './LogisticsManageCn/LostDetails',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/notification',
        name: '消息管理',
        icon: 'sound',
        routes: [
          {
            path: '/notification',
            redirect: '/notification/list',
          },
          {
            path: 'list',
            name: '我的消息',
            access: 'routeFilter',
            component: './Notification/index',
            keepAlive: true,
          },
          {
            path: 'manage',
            name: '发布消息管理',
            access: 'routeFilter',
            component: './Notification/manage',
            keepAlive: true,
          },
          {
            path: 'detail',
            name: '消息详情',
            component: './Notification/detail',
            hideInMenu: true,
          },
          {
            path: 'display',
            name: '消息内容',
            component: './Notification/display',
            hideInMenu: true,
          },
        ],
      },
      {
        path: '/businessOut-manage',
        name: '出差沟通管理',
        icon: 'partition',
        routes: [
          {
            path: '/businessOut-manage',
            redirect: '/businessOut-manage/list',
          },
          {
            path: 'list',
            name: '出差记录',
            access: 'routeFilter',
            component: './BusinessOutManage/List',
            keepAlive: true,
          },
          {
            path: 'communicate',
            name: '沟通记录',
            access: 'routeFilter',
            component: './BusinessOutManage/Communicate',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/storage-manage',
        name: '仓储管理',
        icon: 'shop',
        routes: [
          {
            path: '/storage-manage',
            redirect: '/storage-manage/warehouse',
          },
          {
            path: 'warehouse',
            name: 'CN平台仓管理',
            access: 'routeFilter',
            component: './StorageManage/Warehouse',
            keepAlive: true,
          },
          {
            path: 'warehouseCloud',
            name: '云仓仓库管理',
            access: 'routeFilter',
            component: './StorageManage/WarehouseCloud',
            keepAlive: true,
          },
          {
            path: 'transferWarehouse',
            name: '京东中转仓',
            access: 'routeFilter',
            component: './StorageManage/TransferWarehouse',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/shipment',
        name: 'CN订单配置',
        icon: 'global',
        routes: [
          {
            path: 'express-company',
            name: '快递公司维护',
            access: 'routeFilter',
            component: './shipment/express-company/index',
          },
          {
            path: 'warehouse-cn',
            name: 'CN发货仓管理',
            access: 'routeFilter',
            component: './shipment/warehouse-cn/index',
          },
          {
            path: 'express-warehouse',
            name: '仓库快递配置',
            access: 'routeFilter',
            component: './shipment/express-warehouse/index',
          },
          {
            path: 'warehouse-all',
            name: '发货仓配置',
            access: 'routeFilter',
            component: './shipment/warehouse/index',
          },
        ],
      },
      {
        path: '/setting-manage',
        name: '系统设置',
        icon: 'setting',
        routes: [
          {
            path: '/setting-manage',
            redirect: '/setting-manage/dictList',
            keepAlive: true,
          },
          {
            path: 'dictList',
            name: '数据字典',
            access: 'routeFilter',
            component: './SettingManage/DictList',
          },
          {
            path: 'authority',
            name: '数据权限',
            access: 'routeFilter',
            component: './SettingManage/Authority',
            keepAlive: true,
          },
          {
            path: 'templateDown',
            name: '导入模板管理',
            access: 'routeFilter',
            component: './SettingManage/TemplateDown',
            keepAlive: true,
          },
          {
            path: 'sysVariable',
            name: '变量管理',
            access: 'routeFilter',
            component: './SettingManage/SysVariable',
            keepAlive: true,
          },
          {
            path: 'SerialNumber',
            name: '序列号',
            access: 'routeFilter',
            component: './SettingManage/SerialNumber',
            keepAlive: true,
          },
          {
            path: 'dingDingAudit',
            name: '审批记录',
            access: 'routeFilter',
            component: './SettingManage/DingDingAudit',
            keepAlive: true,
          },
          {
            path: 'erpHistory',
            name: 'ERP同步记录',
            access: 'routeFilter',
            component: './SettingManage/ErpHistory',
            keepAlive: true,
          },
          {
            path: 'form-template',
            name: '请款模板管理',
            access: 'routeFilter',
            component: './Finance/FormTemplate',
            keepAlive: true,
          },
          {
            path: 'linksManage',
            name: '链接设置管理',
            access: 'routeFilter',
            component: './SettingManage/LinksManage',
            keepAlive: true,
          },
          {
            path: 'product-type',
            name: '产品类型',
            access: 'routeFilter',
            component: './SettingManage/ProductType',
            keepAlive: true,
          },
          {
            path: 'monthly-storage-fee',
            name: '月仓储费',
            access: 'routeFilter',
            component: './SettingManage/MonthlyStorageFee',
            keepAlive: true,
          },
          {
            path: 'init-quotation',
            name: '头程报价',
            access: 'routeFilter',
            component: './SettingManage/InitQuotation',
            keepAlive: true,
          },
          {
            path: 'tariff-setting',
            name: '关税设置',
            access: 'routeFilter',
            component: './SettingManage/TariffSetting',
            keepAlive: true,
          },
          {
            path: 'rate-setting',
            name: '汇率设置',
            access: 'routeFilter',
            component: './SettingManage/RateSetting',
            keepAlive: true,
          },
          {
            path: 'rate',
            name: '汇率管理',
            component: './SettingManage/Rate',
            keepAlive: true,
            access: 'routeFilter',
          },
          {
            path: 'liufei',
            name: '导入功能',
            component: './SettingManage/ExportLiuFei',
            hideInMenu: true,
          },
        ],
      },
      {
        path: '/askAction-print',
        layout: false,
        name: '请款记录-打印',
        hideInMenu: true,
        component: './PubPrint/AskAction/print',
      },
      {
        path: '/deduction-print',
        layout: false,
        name: '扣款记录-打印',
        hideInMenu: true,
        component: './PubPrint/Deduction/print',
      },
      {
        path: '/purchase-print',
        layout: false,
        name: '对账-打印',
        hideInMenu: true,
        component: './PubPrint/Purchase/print',
      },
      {
        path: '/scm',
        name: '供应链报表',
        icon: 'pieChart',
        routes: [
          {
            path: '/scm',
            redirect: '/scm/supplier-list',
            keepAlive: true,
          },
          {
            path: 'supplier-list',
            name: '供应商明细表汇总',
            component: './SCM_Manage/SupplierList',
            access: 'routeFilter',
          },
          {
            path: 'product-list',
            name: '商品尺寸',
            component: './SCM_Manage/ProductList',
            access: 'routeFilter',
          },
          {
            path: 'purchase-amount-cn',
            name: 'CN采购金额统计',
            component: './SCM_Manage/PurchaseAmountCN',
            access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'purchase-amount-in',
            name: 'IN采购金额统计',
            component: './SCM_Manage/PurchaseAmountIN',
            access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'products-purchase',
            name: '采购单汇总表',
            noAccessBtnCode: true, // 无'列表查询'按钮, 页面内控制tab显示
            component: './SCM_Manage/ProductsPurchase',
            access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'stock-value-cn',
            name: 'CN库存价值报表',
            component: './SCM_Manage/StockValueCN',
            access: 'routeFilter',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/scm-sales-in',
        name: 'IN销量统计报表',
        icon: 'barChart',
        routes: [
          {
            path: '/scm-sales-in',
            redirect: '/scm-sales-in/storage-value',
            keepAlive: true,
          },
          {
            path: 'storage-value',
            name: 'IN库存价值报表',
            component: './SCM_SALES_IN_Manage/StorageValue',
            access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'amazon-list',
            name: '亚马逊报告',
            component: './SCM_SALES_IN_Manage/OrderList/AmazonList',
            noAccessBtnCode: true,
            access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'walmart-list',
            name: '沃尔玛报告',
            component: './SCM_SALES_IN_Manage/OrderList/WalmartList',
            noAccessBtnCode: true,
            access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'order-statistics-amazon',
            name: '亚马逊销量统计',
            component: './SCM_SALES_IN_Manage/OrderStatistics/Amazon',
            access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'order-statistics-walmart',
            name: '沃尔玛销量统计',
            component: './SCM_SALES_IN_Manage/OrderStatistics/Walmart',
            access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'sales-chart',
            name: 'IN销量曲线图',
            noAccessBtnCode: true,
            component: './SCM_SALES_IN_Manage/SalesChart',
            access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'storage-chart',
            name: 'IN库存曲线图',
            component: './SCM_SALES_IN_Manage/StorageChart',
            access: 'routeFilter',
            keepAlive: true,
          },
          // {
          //   path: 'data-analysis',
          //   name: '销售预测偏差分析',
          //   component: './SCM_SALES_IN_Manage/DataAnalysis',
          // },
        ],
      },
      {
        path: '/after-sales',
        name: '客诉报表',
        icon: 'barChart',
        routes: [
          {
            path: '/after-sales',
            redirect: '/after-sales/return-exchange',
            keepAlive: true,
          },
          {
            path: 'return-exchange',
            name: 'IN客诉率统计',
            component: './after-sales/return-exchange',
            access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'feedback-detail',
            name: 'IN客诉明细',
            component: './after-sales/feedback-detail',
            access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'feedback-classify',
            name: 'IN客诉分类统计(自定义)',
            component: './after-sales/feedback-classify',
            access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'feedback-plat',
            name: 'IN客诉分类统计(平台)',
            component: './after-sales/feedback-plat',
            access: 'routeFilter',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/cn-sales',
        name: 'CN销量报表',
        icon: 'barChart',
        routes: [
          {
            path: '/cn-sales',
            redirect: '/cn-sales/jd-self-daily',
            keepAlive: true,
          },
          {
            path: 'cn-sales-daily',
            name: '京东自营销量',
            component: './cn-sales/cn-sales-daily',
            access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'jd-region',
            name: 'CN销量区域归属配置',
            component: './cn-sales/jd-region',
            access: 'routeFilter',
          },
          {
            path: 'cn-sales-statistics',
            name: 'CN销售统计报表',
            component: './cn-sales/cn-sales-statistics',
            access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'cn-sales-statistics1',
            name: 'CN销售统计报表',
            component: './cn-sales/cn-sales-statistics/index2',
            // access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'cn-sales-chart',
            name: 'CN销售曲线图',
            component: './cn-sales/cn-sales-chart',
            access: 'routeFilter',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/cn-stockup',
        name: 'CN备货报表',
        icon: 'barChart',
        routes: [
          {
            path: 'stock-sale-h',
            name: 'CN库存-销量汇总(横版)',
            component: './cn-stockup/stock-sale-hv',
            access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'stock-sale-v',
            name: 'CN库存-销量汇总(竖版)',
            component: './cn-stockup/stock-sale-vv',
            access: 'routeFilter',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/amazon-sale-order',
        name: '亚马逊销量统计报表',
        icon: 'global',
        routes: [
          {
            path: 'order-list',
            name: '订单统计',
            access: 'routeFilter',
            component: './amazon-sale-order/order-list',
            keepAlive: true,
          },
          {
            path: 'order-chart',
            name: '销量曲线图',
            access: 'routeFilter',
            component: './amazon-sale-order/order-chart',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/setting-manage-report',
        name: '系统设置',
        icon: 'setting',
        routes: [
          {
            path: '/setting-manage-report',
            redirect: '/setting-manage-report/rules',
            keepAlive: true,
          },
          {
            path: 'rules',
            name: '规则列表',
            component: './ReportSettingManage/Rules',
            access: 'routeFilter',
            keepAlive: true,
          },
          {
            path: 'rules/detail',
            parentKeys: ['/setting-manage-report/rules'],
            name: '规则详情',
            hideInMenu: true,
            component: './ReportSettingManage/Rules/detail',
          },
          {
            path: 'custom-tag',
            name: '自定义客诉标签',
            component: './ReportSettingManage/custom-tag',
            access: 'routeFilter',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/callBack',
        name: '回调补偿管理',
        component: './AmsManage/CallbackManage',
        access: 'routeFilter',
        keepAlive: true,
      },
      {
        path: '/amazon/report',
        name: '亚马逊报告下载管理',
        access: 'routeFilter',
        component: './AmsManage/AmazonReportD',
        keepAlive: true,
      },
      {
        path: '/order',
        name: 'CN订单管理',
        routes: [
          {
            path: 'order-list',
            name: 'CN订单列表',
            icon: 'global',
            access: 'routeFilter',
            component: './order/order/index',
            keepAlive: true,
          },
          {
            path: 'delivery-order',
            name: 'CN配送单',
            access: 'routeFilter',
            icon: 'shop',
            component: './order/delivery-order/index',
          },
          {
            path: 'sales-refund',
            name: 'CN销退单',
            icon: 'RollbackOutlined',
            access: 'routeFilter',
            component: './order/sales-refund',
          },
        ],
      },
      {
        path: '/ams',
        name: '权限系统',
        routes: [
          {
            path: 'apps',
            name: '应用管理',
            icon: 'global',
            access: 'routeFilter',
            component: './AmsManage/App',
            keepAlive: true,
          },
          {
            path: 'menus',
            name: '菜单管理',
            icon: 'global',
            access: 'routeFilter',
            component: './AmsManage/Menus',
            keepAlive: true,
          },
          {
            path: 'roles',
            name: '角色管理',
            icon: 'global',
            access: 'routeFilter',
            component: './AmsManage/Roles',
            keepAlive: true,
          },
          {
            path: 'roles/roleDetail',
            name: '角色分配权限',
            icon: 'global',
            component: './AmsManage/Roles/roleProsDetail',
            hideInMenu: true,
          },
          {
            path: 'roles/roleMenuDetail',
            name: '查看权限',
            icon: 'global',
            component: './AmsManage/Roles/roleMenuDetail',
            hideInMenu: true,
          },
          {
            path: 'roles/roleUser',
            name: '角色分配用户',
            icon: 'global',
            component: './AmsManage/Roles/roleUser',
            hideInMenu: true,
          },
          {
            path: 'roles/editRolesPromiss',
            name: '批量编辑角色权限',
            icon: 'global',
            component: './AmsManage/Roles/editRolesPromiss',
            hideInMenu: true,
          },
          {
            path: 'users',
            name: '用户授权',
            icon: 'global',
            access: 'routeFilter',
            component: './AmsManage/Users',
            keepAlive: true,
          },
          {
            path: 'comFunction',
            name: '后台接口管理',
            icon: 'global',
            access: 'routeFilter',
            component: './AmsManage/ComFunction',
            keepAlive: true,
          },
          {
            path: 'applyList',
            name: '审批管理',
            icon: 'global',
            access: 'routeFilter',
            component: './AmsManage/ApplyList',
            keepAlive: true,
          },
          {
            path: 'systemLog',
            name: '日志管理',
            icon: 'global',
            access: 'routeFilter',
            component: './AmsManage/LogManage',
            keepAlive: true,
          },
          {
            path: 'systemAuditLog',
            name: '审计日志',
            icon: 'global',
            access: 'routeFilter',
            component: './AmsManage/AuditLog',
            keepAlive: true,
          },
          {
            path: 'systemCache',
            name: '缓存管理',
            icon: 'global',
            access: 'routeFilter',
            component: './AmsManage/Cache',
            keepAlive: true,
          },
          {
            path: 'systemToken',
            name: 'Token管理',
            icon: 'global',
            access: 'routeFilter',
            component: './AmsManage/Token',
            keepAlive: true,
          },
          {
            path: 'dingdingTalk',
            name: '钉钉',
            icon: 'global',
            access: 'routeFilter',
            component: './AmsManage/DingDingTalk',
            keepAlive: true,
          },
        ],
      },
      {
        name: '自有仓',
        path: '/warehouse',
        routes: [
          {
            name: '入库管理',
            path: 'input',
            routes: [
              {
                name: '退货入库',
                path: 'return-build',
                component: './warehouse/input/return-build',
                access: 'routeFilter',
                keepAlive: true,
              },
              {
                name: '采购入库(包材配件)',
                path: 'po-build',
                component: './warehouse/input/po-build',
                access: 'routeFilter',
                keepAlive: true,
              },
              {
                name: '退货入库单',
                path: 'return-list',
                component: './warehouse/input/return-list',
                access: 'routeFilter',
                keepAlive: true,
              },
              {
                name: '退货入库单-详情',
                path: 'return-list-detail',
                component: './warehouse/input/return-list-detail',
                keepAlive: true,
              },
              {
                name: '包材配件入库单',
                path: 'po-list',
                component: './warehouse/input/po-list',
                access: 'routeFilter',
                keepAlive: true,
              },
              {
                name: '包材配件入库单-详情',
                path: 'po-list-detail',
                component: './warehouse/input/po-list-detail',
                keepAlive: true,
              },
            ],
          },
          {
            name: '库存管理',
            path: 'stock',
            routes: [
              {
                name: '退货库存',
                path: 'return',
                component: './warehouse/stock/return',
                access: 'routeFilter',
                keepAlive: true,
              },
              {
                name: '包材配件库存',
                path: 'po',
                component: './warehouse/stock/po',
                access: 'routeFilter',
                keepAlive: true,
              },
              {
                name: '盘点管理',
                path: 'check',
                component: './warehouse/stock/check',
                access: 'routeFilter',
                keepAlive: true,
              },
              {
                name: '盘点管理 - 详情',
                path: 'check-detail',
                component: './warehouse/stock/check-detail',
                keepAlive: true,
              },
              {
                name: '良品转不良品',
                path: 'transform',
                component: './warehouse/stock/transform',
                access: 'routeFilter',
                keepAlive: true,
              },
              {
                name: '良品转不良品 - 详情',
                path: 'transform-detail',
                component: './warehouse/stock/transform-detail',
                keepAlive: true,
              },
            ],
          },
          {
            name: '出库管理',
            path: 'output',
            routes: [
              {
                name: '包材配件领用出库',
                path: 'po',
                component: './warehouse/output/po',
                access: 'routeFilter',
                keepAlive: true,
              },
              {
                name: '包材配件领用出库 - 详情',
                path: 'po-detail',
                component: './warehouse/output/po-detail',
                keepAlive: true,
              },
              {
                name: '不良品出库',
                path: 'scrap',
                component: './warehouse/output/scrap',
                access: 'routeFilter',
                keepAlive: true,
              },
              {
                name: '不良品出库 - 详情',
                path: 'scrap-detail',
                component: './warehouse/output/scrap-detail',
                keepAlive: true,
              },
            ],
          },
        ],
      },
      {
        path: '/finance',
        name: '财务',
        routes: [
          {
            path: '/finance',
            redirect: '/finance/askOrder',
          },
          {
            path: 'askOrder',
            name: '请款单',
            access: 'routeFilter',
            component: './Finance/AskOrder',
            keepAlive: true,
          },
          {
            path: 'deposit',
            name: '押金管理',
            access: 'routeFilter',
            component: './Finance/Deposit',
            keepAlive: true,
          },
        ],
      },
      {
        path: '/askOrder-print',
        layout: false,
        name: '请款单打印',
        hideInMenu: true,
        component: './Finance/AskOrder/Print',
      },
      {
        component: './404',
      },
    ],
  },
];
